export const INNERTUBE_API_KEY = 'INNERTUBE_API_KEY'
export const INNERTUBE_CONTEXT = 'INNERTUBE_CONTEXT'
export const VISITOR_DATA = 'VISITOR_DATA'
export const YTMUSIC_INITIAL_DATA = 'YTMUSIC_INITIAL_DATA'
