import swaggerAutogen from "swagger-autogen"
import path from "path"

const outputFile = path.join(__dirname, "..", "..", "docs", "swagger_output.json")
const endpointsFiles = [path.join(__dirname, "..", "server.ts")]

const doc = {
    info: {
        version: "1.0.0",
        title: "Mysic API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Home",
            "description": "Endpoints"
        },
        {
            "name": "Browse",
            "description": "Endpoints"
        },
        {
            "name": "Explorer",
            "description": "Endpoints"
        },
        {
            "name": "Search",
            "description": "Endpoints"
        }
    ],
    definitions: {
        HomeResult: {
            data: [
                {
                    section: "Quick picks",
                    type: "song",
                    contents: [
                        {
                            "videoId": "I3zqu9yM2fA",
                            "title": "DJ KUDA YANG MANA KUDA YANG MANA FULL BASS 2023 VIRAL",
                            "subtitle": "Bumi Sunda",
                            "thumbnails": [
                                {
                                "url": "https://lh3.googleusercontent.com/SpN189BTkd97ygCP28L89eRqzVjtzrpwVEnp7OThqGPfY99qJKinFDsIOEeGxmjtuCu-mUcHw70ePxvb=w60-h60-l90-rj",
                                "width": 60,
                                "height": 60
                                },
                                {
                                "url": "https://lh3.googleusercontent.com/SpN189BTkd97ygCP28L89eRqzVjtzrpwVEnp7OThqGPfY99qJKinFDsIOEeGxmjtuCu-mUcHw70ePxvb=w120-h120-l90-rj",
                                "width": 120,
                                "height": 120
                                },
                                {
                                "url": "https://lh3.googleusercontent.com/SpN189BTkd97ygCP28L89eRqzVjtzrpwVEnp7OThqGPfY99qJKinFDsIOEeGxmjtuCu-mUcHw70ePxvb=w720-h720-l90-rj",
                                "width": 720,
                                "height": 720
                                }
                            ]
                        },
                        {
                            "section": "Today's International hits",
                            "type": "browse",
                            "contents": [
                                {
                                    "title": "RELEASED",
                                    "browseId": "VLRDCLAK5uy_nMln2JPa-4fhqwquE3dRinwNr6IkN2-7k",
                                    "subtitle": "EXO, KAIYI, Sutter, Icona Pop",
                                    "thumbnails": [
                                        {
                                            "url": "https://lh3.googleusercontent.com/u4h-a2v2ET2qACtuJNEpu5ib6KoeKrRy1pvJLKbDBpincd6amB9ygT7QtzLwJV3pgEWyvZBc3Mt0DvmV=w226-h226-l90-rj",
                                            "width": 226,
                                            "height": 226
                                        },
                                        {
                                            "url": "https://lh3.googleusercontent.com/u4h-a2v2ET2qACtuJNEpu5ib6KoeKrRy1pvJLKbDBpincd6amB9ygT7QtzLwJV3pgEWyvZBc3Mt0DvmV=w544-h544-l90-rj",
                                            "width": 544,
                                            "height": 544
                                        },
                                        {
                                            "url": "https://lh3.googleusercontent.com/u4h-a2v2ET2qACtuJNEpu5ib6KoeKrRy1pvJLKbDBpincd6amB9ygT7QtzLwJV3pgEWyvZBc3Mt0DvmV=w720-h720-l90-rj",
                                            "width": 720,
                                            "height": 720
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            continuation: "4qmFsgKFAhIMRkVtdXNpY19ob21lGvQBQ0FONnNnRkhUR1ZGT1dSeFNXMVpRVVJYYmtsTFkwRnZhMlZZVW1aalIwWnVXbFk1ZW1KdFJuZGpNbWgyWkVZNWRHUllUbkJaTVRsM1dWZGtiRmd6U214YU1teDJZbTFHYzBWb09WWlBWVTVoV210Vk5FMVliR1prTVd4T1UxWmtSbE13Y0UxTk0wVjBVV3RXYTFVelJuaGlSMmh1UjJsalFVRkhWblZCUVVaS1VrRkJRbE5WVVVGQlVVSkhVbGN4TVdNeWJHcFlNbWgyWWxkVlFVRlJSa1JCUVVGQ1FVRkJRa0ZSUkRadVRXVTVRMUZKU1VKQg%3D%3D"
        },
        BrowseNextResult: {
            "type": "song",
            "contents": [
                {
                    "videoId": "cuJUl1WYjfM",
                    "title": "Eye On The Bat",
                    "subtitle": "Palehound",
                    "thumbnails": [
                        {
                            "url": "https://lh3.googleusercontent.com/6f2V_M3prgDLaO5RiIe0COP2XJU5F558M_KDfypb4k1mPlQ72DsgDLt3H-rClCmSoErIOu998L0FRemgpQ=w60-h60-l90-rj",
                            "width": 60,
                            "height": 60
                        },
                        {
                            "url": "https://lh3.googleusercontent.com/6f2V_M3prgDLaO5RiIe0COP2XJU5F558M_KDfypb4k1mPlQ72DsgDLt3H-rClCmSoErIOu998L0FRemgpQ=w120-h120-l90-rj",
                            "width": 120,
                            "height": 120
                        },
                        {
                            "url": "https://lh3.googleusercontent.com/6f2V_M3prgDLaO5RiIe0COP2XJU5F558M_KDfypb4k1mPlQ72DsgDLt3H-rClCmSoErIOu998L0FRemgpQ=w720-h720-l90-rj",
                            "width": 720,
                            "height": 720
                        }
                    ],
                    "duration": "2:57",
                    "totalDuration": 177
                    }
            ]
        },
        SearchDefaultResult: {
            contents: [
                {
                    "videoId": "VD4PYP7WUCA",
                    "title": "The Unforgiven III",
                    "subtitle": "Song • Metallica • Death Magnetic • 7:47",
                    "thumbnails": [
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w60-h60-l90-rj",
                            "width": 60,
                            "height": 60
                        },
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w120-h120-l90-rj",
                            "width": 120,
                            "height": 120
                        },
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w720-h720-l90-rj",
                            "width": 720,
                            "height": 720
                        }
                    ],
                    "duration": "7:47",
                    "totalDuration": 467
                },
            ],
            "nextAction": {
                "next": "EgWKAQIIAWoOEAMQCRAEEA4QChAFEBU%3D",
                "q": "metallica"
            }
        },
        SearchNextResult: {
            contents: [
                {
                    "videoId": "VD4PYP7WUCA",
                    "title": "The Unforgiven III",
                    "subtitle": "Song • Metallica • Death Magnetic • 7:47",
                    "thumbnails": [
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w60-h60-l90-rj",
                            "width": 60,
                            "height": 60
                        },
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w120-h120-l90-rj",
                            "width": 120,
                            "height": 120
                        },
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w720-h720-l90-rj",
                            "width": 720,
                            "height": 720
                        }
                    ],
                    "duration": "7:47",
                    "totalDuration": 467
                },
            ],
            "nextAction": {
                ct: "EqgDEgltZXRhbGxpY2EamgNFZ1dLQVFJSUFVZ1VhZzRRQXhBSkVBUVFEaEFLRUFVUUZZSUJDM0JVV1VsbU1uQnJlSHBSZ2dFTFJUQnZlbTFWT1dOS1JHZUNBUXMwTnpkMGNrRlRWM1ZEU1lJQkMydEhXVVF6YUd0RFVFRmpnZ0VMU2xFMmNIbHJTVE5JY2xtQ0FRdHRPRVJKTFZOUlgxUm9kNElCQzBWeWN6UjNSWFJsYTBscmdnRUxWa1EwVUZsUU4xZFZRMEdDQVF0d00zSndXakV0UkdOMFo0SUJDM2hqTjNrNVZUWlhhMUF3Z2dFTE1ISldTVVZxTjNwblQyLUNBUXRSY1ZkQ1MxVlJhSGRQVllJQkMyUnZiV3B4YWxGZlYxSkpnZ0VMYldsVVJVRnZSWFpvYTFHQ0FRdERTRWxYVGtSQmQxUnhVWUlCQzBkclZVTTBORU5YZDJwM2dnRUxOVUZZWkVObmIzbFZXSE9DQVF0R1RGUmphRU5wUXpCVU1JSUJDMUoyVnpSUFVVWkJYMVZaZ2dFTE1XSlhNa1JOVDJWRVJVMCUzRBjx6tAu"
            }
        },
         SearchContinuationResult: {
            contents: [
                {
                    "videoId": "VD4PYP7WUCA",
                    "title": "The Unforgiven III",
                    "subtitle": "Song • Metallica • Death Magnetic • 7:47",
                    "thumbnails": [
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w60-h60-l90-rj",
                            "width": 60,
                            "height": 60
                        },
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w120-h120-l90-rj",
                            "width": 120,
                            "height": 120
                        },
                        {
                            "url": "https://lh3.googleusercontent.com/jKSy3N15Nd2vF0OG4m10y4A-GgN94CJQIyseGZ0HjJIDUL9dqfY1SI4mqOuJkuUdmaOQ-HRI9q_9BXo=w720-h720-l90-rj",
                            "width": 720,
                            "height": 720
                        }
                    ],
                    "duration": "7:47",
                    "totalDuration": 467
                },
            ],
            "nextAction": {
                ct: "EqgDEgltZXRhbGxpY2EamgNFZ1dLQVFJSUFVZ1VhZzRRQXhBSkVBUVFEaEFLRUFVUUZZSUJDM0JVV1VsbU1uQnJlSHBSZ2dFTFJUQnZlbTFWT1dOS1JHZUNBUXMwTnpkMGNrRlRWM1ZEU1lJQkMydEhXVVF6YUd0RFVFRmpnZ0VMU2xFMmNIbHJTVE5JY2xtQ0FRdHRPRVJKTFZOUlgxUm9kNElCQzBWeWN6UjNSWFJsYTBscmdnRUxWa1EwVUZsUU4xZFZRMEdDQVF0d00zSndXakV0UkdOMFo0SUJDM2hqTjNrNVZUWlhhMUF3Z2dFTE1ISldTVVZxTjNwblQyLUNBUXRSY1ZkQ1MxVlJhSGRQVllJQkMyUnZiV3B4YWxGZlYxSkpnZ0VMYldsVVJVRnZSWFpvYTFHQ0FRdERTRWxYVGtSQmQxUnhVWUlCQzBkclZVTTBORU5YZDJwM2dnRUxOVUZZWkVObmIzbFZXSE9DQVF0R1RGUmphRU5wUXpCVU1JSUJDMUoyVnpSUFVVWkJYMVZaZ2dFTE1XSlhNa1JOVDJWRVJVMCUzRBjx6tAu"
            }
        },
        ExplorerDefaultResult: {
            "data": [
                {
                    "section": "New albums & singles",
                    "type": "browse",
                    "contents": [
                        {
                            "title": "Speak Now (Taylor's Version)",
                            "browseId": "MPREb_7u82vYqpamW",
                            "subtitle": "Album • Taylor Swift",
                            "thumbnails": [
                                {
                                    "url": "https://lh3.googleusercontent.com/PzdFvhZwBo2kxfifFF82vShEUh8xEQfvoUTRIUBvZjs3ibCmTqMQZ6ZL03tPz1iwjP4UH6xB0CAGPwqj=w226-h226-l90-rj",
                                    "width": 226,
                                    "height": 226
                                },
                                {
                                    "url": "https://lh3.googleusercontent.com/PzdFvhZwBo2kxfifFF82vShEUh8xEQfvoUTRIUBvZjs3ibCmTqMQZ6ZL03tPz1iwjP4UH6xB0CAGPwqj=w544-h544-l90-rj",
                                    "width": 544,
                                    "height": 544
                                },
                                {
                                    "url": "https://lh3.googleusercontent.com/PzdFvhZwBo2kxfifFF82vShEUh8xEQfvoUTRIUBvZjs3ibCmTqMQZ6ZL03tPz1iwjP4UH6xB0CAGPwqj=w720-h720-l90-rj",
                                    "width": 720,
                                    "height": 720
                                }
                            ]
                        },
                    ]
                },
                {
                    "section": "Moods & genres",
                    "type": "genre",
                    "contents": [
                        {
                        "title": "Chill",
                        "browseId": "FEmusic_moods_and_genres_category",
                        "params": "ggMPOg1uX1JOQWZFeDByc2Jm",
                        "color": "#ffa4c5ff"
                        },
                    ]
                },
                {
                    "section": "Trending",
                    "type": "song",
                    "contents": [
                        {
                            "videoId": "QU9c0053UAU",
                            "title": "Seven (feat. Latto)",
                            "subtitle": "Jung Kook • 72M views",
                            "thumbnails": [
                                {
                                    "url": "https://i.ytimg.com/vi/QU9c0053UAU/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3ki23gt683kPaAs_tipdild1wrLTQ",
                                    "width": 400,
                                    "height": 225
                                },
                                {
                                    "url": "https://i.ytimg.com/vi/QU9c0053UAU/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3ki23gt683kPaAs_tipdild1wrLTQ",
                                    "width": 720,
                                    "height": 720
                                }
                            ],
                            "duration": "72M views",
                            "totalDuration": 72
                        }
                    ]
                }
            ]
        },
        ExplorerNextResult: {
            "type": "song",
            "contents": [
                {
                    "videoId": "oxNLRqMJMZk",
                    "title": "Mine (Taylor's Version)",
                    "duration": "3:52",
                    "totalDuration": 232
                },
            ]
        },
        ExplorerNextParamResult: {
            data: [
                {
                    "section": "Coffee shop blends",
                    "type": "browse",
                    "contents": [
                        {
                            "title": "Café Hits",
                            "browseId": "VLRDCLAK5uy_m5qG4ExqLirXAM7qVrSJFgemYrNzuP4js",
                            "subtitle": "Playlist • YouTube Music",
                            "thumbnails": [
                                {
                                    "url": "https://lh3.googleusercontent.com/-DUA7w57wuDybKVO84upkSsm3YipitP0RSnKvEX_AO9y6nB7NXydr6mL6p1W6nL1Ifutm_VfMU96G7FW=w226-h226-l90-rj",
                                    "width": 226,
                                    "height": 226
                                },
                                {
                                    "url": "https://lh3.googleusercontent.com/-DUA7w57wuDybKVO84upkSsm3YipitP0RSnKvEX_AO9y6nB7NXydr6mL6p1W6nL1Ifutm_VfMU96G7FW=w544-h544-l90-rj",
                                    "width": 544,
                                    "height": 544
                                },
                                {
                                    "url": "https://lh3.googleusercontent.com/-DUA7w57wuDybKVO84upkSsm3YipitP0RSnKvEX_AO9y6nB7NXydr6mL6p1W6nL1Ifutm_VfMU96G7FW=w720-h720-l90-rj",
                                    "width": 720,
                                    "height": 720
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        PlayResult: {
            "mimeType": "audio/webm; codecs=\"opus\"",
            "qualityLabel": null,
            "bitrate": 141866,
            "audioBitrate": 160,
            "itag": 251,
            "initRange": {
                "start": "0",
                "end": "265"
            },
            "indexRange": {
                "start": "266",
                "end": "670"
            },
            "lastModified": "1662279364040056",
            "contentLength": "3913926",
            "quality": "tiny",
            "projectionType": "RECTANGULAR",
            "averageBitrate": 134997,
            "audioQuality": "AUDIO_QUALITY_MEDIUM",
            "approxDurationMs": "231941",
            "audioSampleRate": "48000",
            "audioChannels": 2,
            "loudnessDb": 4.3999996,
            "url": "audio URL",
            "hasVideo": false,
            "hasAudio": true,
            "container": "webm",
            "codecs": "opus",
            "videoCodec": null,
            "audioCodec": "opus",
            "isLive": false,
            "isHLS": false,
            "isDashMPD": false
        },
        ErrorResult: {
            error: "<error info>",
            msg: 'something went wrong'
        },
        Error422Result: {
            error: "<error info>"
        }
    }
}

Object.assign(doc.definitions, {BrowseContinuationResult: doc.definitions.HomeResult})

// @ts-ignore: Unreachable code error
swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
    await import("../routes")
})